export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { to, freelancerName, taskTitle, campaignTitle, contract, creatorName } = req.body;

  if (!to || !contract) return res.status(400).json({ error: 'Missing required fields' });

  // Convert markdown bold to HTML
  const contractHtml = contract
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br/>');

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <style>
    body { font-family: 'Georgia', serif; background: #F7F4EE; margin: 0; padding: 0; }
    .wrapper { max-width: 620px; margin: 0 auto; padding: 40px 20px; }
    .header { background: #18160F; padding: 28px 32px; border-radius: 12px 12px 0 0; }
    .logo { font-size: 22px; color: #fff; font-weight: 700; margin: 0; }
    .logo span { color: #F5A623; }
    .body { background: #fff; padding: 36px 32px; border-radius: 0 0 12px 12px; border: 1px solid #DDD8CE; border-top: none; }
    .greeting { font-size: 18px; color: #18160F; margin-bottom: 8px; font-weight: 600; }
    .intro { font-size: 14px; color: #7A7669; line-height: 1.6; margin-bottom: 28px; }
    .contract-box { background: #F7F4EE; border: 1px solid #DDD8CE; border-radius: 10px; padding: 24px; margin-bottom: 24px; font-size: 13px; color: #3D3A30; line-height: 1.7; }
    .contract-box p { margin: 0 0 12px; }
    .contract-box p:last-child { margin-bottom: 0; }
    .cta { background: #D4820A; color: #fff; padding: 14px 28px; border-radius: 8px; text-decoration: none; font-size: 14px; font-weight: 700; display: inline-block; margin-bottom: 24px; }
    .footer { font-size: 12px; color: #7A7669; text-align: center; margin-top: 24px; line-height: 1.6; }
    .divider { height: 1px; background: #DDD8CE; margin: 20px 0; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <p class="logo">Creator<span>OS</span></p>
    </div>
    <div class="body">
      <div class="greeting">Hi ${freelancerName} 👋</div>
      <div class="intro">
        You've been matched to a campaign on CreatorOS! <strong>${creatorName}</strong> has selected you for the following work. Please review the Statement of Work below and reply to confirm your acceptance.
      </div>
      <div style="background:#EAFAF1;border:1px solid #27AE60;border-radius:8px;padding:14px 18px;margin-bottom:20px;">
        <div style="font-size:13px;font-weight:700;color:#2E7D32;">📋 ${taskTitle}</div>
        <div style="font-size:12px;color:#27AE60;margin-top:3px;">Campaign: ${campaignTitle}</div>
      </div>
      <div class="contract-box">
        <p>${contractHtml}</p>
      </div>
      <div class="divider"></div>
      <div style="font-size:13px;color:#7A7669;line-height:1.6;">
        To accept this contract, simply reply to this email with <strong>"I accept"</strong>. Work should not begin until you've confirmed acceptance and the initial payment has been secured in escrow.
      </div>
      <div class="footer">
        This contract was generated by CreatorOS · <a href="https://creatoros.co.in" style="color:#D4820A;">creatoros.co.in</a><br/>
        Questions? Reply to this email.
      </div>
    </div>
  </div>
</body>
</html>`;

  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.RESEND_API_KEY}`
      },
      body: JSON.stringify({
        from: 'CreatorOS <onboarding@resend.dev>',
        to: [to],
        subject: `📋 Contract: ${taskTitle} — ${campaignTitle}`,
        html
      })
    });

    const data = await response.json();
    if (!response.ok) return res.status(500).json({ error: data.message || 'Email failed' });
    return res.status(200).json({ success: true, id: data.id });

  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}
